CREATE DATABASE IF NOT EXISTS cadastro_clientes CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cadastro_clientes;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  telefone VARCHAR(30),
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
